### ISSUE TITLE
Bedriftsprofiler skal kunne bla gjennom én profil av gangen

### ISSUE THREAD

**Issue by hanscjo** [sjojon/GET_Partner#16]
Det vil si slide 9 i figma, at man får opp en profil med mer detaljert info

**Comment by VictorVariety** [comment]
Så og si ferdig, men mangler kartet og funksjonalitet i knappene. Kanskje lage en knapp til mellom trekant knappene ellerno som tar en tilbake til søkesiden med søke kriteriene de hadde lagt inn allerede
