### ISSUE TITLE
Bruker skal kunne navigere med navigasjonsbar

### ISSUE THREAD

**Issue by hanscjo** [sjojon/GET_Partner#18]
-navigasjonsbar skal inneholde flere link som leder til ulike sider.
-hvis bruker trykker på en link som leder ut av “currentPage” FØR hen har lagret info, skal en alert dukke opp.

**Comment by thesneilert** [comment]
Navigasjonsbar er laget og designet, ikke lagt til funksjoner eller linker.
Menyen har dropdown funksjon i controller.

**Comment by thesneilert** [comment]
Lagt til "go to home" funksjon på logoen i header.

**Comment by thesneilert** [comment]
Lagt til "go to login" funksjon i header.

**Comment by thesneilert** [comment]
Så og si ferdig, mangler bare riktige knapper og goTo etterfølgende.

**Comment by thesneilert** [comment]
Gjort om hele MVC til header og laget dynamisk header til forskjellige sider.
